version: '3.4'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'FischQuiz'
      MYSQL_USER: 'fischuser'
      MYSQL_PASSWORD: example
    ports:
      - '9999:3306'
    volumes:
      - fish-db:/var/lib/mysql

  fischquizapi:
    image: qeex/fischquizapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8066:80"
    depends_on:
      - db

volumes:
  fish-db: