name: CI/CD

on: 
  push
      
env:
  ContainerName: fishquizfrontend

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: show everything
        run: echo "some data is ${{ vars.NEXT_PUBLIC_API_URL }}"

      - name: Build Container
        uses: docker/build-push-action@v4
        with:
          context: ./client/
          push: true
          tags: qeex/fischquizui:latest-pip
          build-args: |
            "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}"

