name: CI/CD

on:
  push:
    branches: [ "main" ]

env:
  ContainerName: fishquizfrontend

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./client/fisch-quiz/Dockerfile
          push: true
          tags: qeex/${{ env.ContainerName }}:latest

