name: CI/CD

on: 
  push
      
env:
  ContainerName: dada

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Container
        uses: docker/build-push-action@v4
        with:
          context: ./client/
          push: true
          tags: name/dat:latest-pip
          build-args: |
            process.env.NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}

